### ISSUE TITLE
Recent Receipts are not ordered by date in Main Activity

### ISSUE THREAD

**Issue by chriszaro** [chriszaro/Tefteri#8]

**Comment by chriszaro** [comment]
Νομίζω πως τα ταξινομεί λεξικογραφικά και όχι ως ημερομηνίες. Ίσως πρέπει να γίνει αλλαγή τύπου δεδομένων στην βάση.

**Comment by chriszaro** [comment]
Maybe remove 269-281 in MainActivity (ο τέλειος κώδικάς μου για μετατροπή ημερομηνιών)

**Comment by lazarosgogos** [comment]
#15
